// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Peer struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	PublicKey string             `json:"public_key"`
	IpAddress netip.Addr         `json:"ip_address"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ServerConfig struct {
	ID            pgtype.UUID        `json:"id"`
	InterfaceName string             `json:"interface_name"`
	PublicKey     string             `json:"public_key"`
	ListenPort    int32              `json:"listen_port"`
	IpPool        netip.Prefix       `json:"ip_pool"`
	Dns           []string           `json:"dns"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	PublicKey pgtype.Text        `json:"public_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
