// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPeer = `-- name: CreatePeer :one
INSERT INTO peers (user_id, name, public_key, allowed_ips)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, public_key, allowed_ips, enabled, created_at, updated_at
`

type CreatePeerParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Name       string      `json:"name"`
	PublicKey  string      `json:"public_key"`
	AllowedIps []string    `json:"allowed_ips"`
}

func (q *Queries) CreatePeer(ctx context.Context, arg CreatePeerParams) (Peer, error) {
	row := q.db.QueryRow(ctx, createPeer,
		arg.UserID,
		arg.Name,
		arg.PublicKey,
		arg.AllowedIps,
	)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.AllowedIps,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePeer = `-- name: DeletePeer :exec
DELETE FROM peers WHERE id = $1
`

func (q *Queries) DeletePeer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePeer, id)
	return err
}

const disablePeer = `-- name: DisablePeer :exec
UPDATE peers SET enabled = FALSE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DisablePeer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disablePeer, id)
	return err
}

const enablePeer = `-- name: EnablePeer :exec
UPDATE peers SET enabled = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) EnablePeer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, enablePeer, id)
	return err
}

const getPeer = `-- name: GetPeer :one
SELECT id, user_id, name, public_key, allowed_ips, enabled, created_at, updated_at FROM peers WHERE id = $1
`

func (q *Queries) GetPeer(ctx context.Context, id pgtype.UUID) (Peer, error) {
	row := q.db.QueryRow(ctx, getPeer, id)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.AllowedIps,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeerByPublicKey = `-- name: GetPeerByPublicKey :one
SELECT id, user_id, name, public_key, allowed_ips, enabled, created_at, updated_at FROM peers WHERE public_key = $1
`

func (q *Queries) GetPeerByPublicKey(ctx context.Context, publicKey string) (Peer, error) {
	row := q.db.QueryRow(ctx, getPeerByPublicKey, publicKey)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.AllowedIps,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPeers = `-- name: ListEnabledPeers :many
SELECT id, user_id, name, public_key, allowed_ips, enabled, created_at, updated_at FROM peers WHERE enabled = TRUE ORDER BY created_at
`

func (q *Queries) ListEnabledPeers(ctx context.Context) ([]Peer, error) {
	rows, err := q.db.Query(ctx, listEnabledPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Peer
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.AllowedIps,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeersByUser = `-- name: ListPeersByUser :many
SELECT id, user_id, name, public_key, allowed_ips, enabled, created_at, updated_at FROM peers WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListPeersByUser(ctx context.Context, userID pgtype.UUID) ([]Peer, error) {
	rows, err := q.db.Query(ctx, listPeersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Peer
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.AllowedIps,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeerAllowedIPs = `-- name: UpdatePeerAllowedIPs :one
UPDATE peers SET allowed_ips = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, user_id, name, public_key, allowed_ips, enabled, created_at, updated_at
`

type UpdatePeerAllowedIPsParams struct {
	AllowedIps []string    `json:"allowed_ips"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePeerAllowedIPs(ctx context.Context, arg UpdatePeerAllowedIPsParams) (Peer, error) {
	row := q.db.QueryRow(ctx, updatePeerAllowedIPs, arg.AllowedIps, arg.ID)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.AllowedIps,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
