// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePeer(ctx context.Context, arg CreatePeerParams) (Peer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePeer(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DisablePeer(ctx context.Context, id pgtype.UUID) error
	EnablePeer(ctx context.Context, id pgtype.UUID) error
	GetPeer(ctx context.Context, id pgtype.UUID) (Peer, error)
	GetPeerByPublicKey(ctx context.Context, publicKey string) (Peer, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListEnabledPeers(ctx context.Context) ([]Peer, error)
	ListPeersByUser(ctx context.Context, userID pgtype.UUID) ([]Peer, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdatePeerAllowedIPs(ctx context.Context, arg UpdatePeerAllowedIPsParams) (Peer, error)
	UpdateUserPublicKey(ctx context.Context, arg UpdateUserPublicKeyParams) (User, error)
}

var _ Querier = (*Queries)(nil)
